name: CI Simple

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests Results
          path: '**/build/test-results/test/*.xml'
          reporter: java-junit

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/test/